### ISSUE TITLE
Replace match submission user with tournament submission user

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#112]
Considering users are only supposed to submit tournaments, not individual matches (and, all individual matches are tied to a parent tournament), we need to identify who the tournament submitter is instead of the match submitter.

This requires modifying the database and a database script to migrate submitter ids. I think it's fine to just take the first match from each tournament, get the `submitted_by_user`, and move the id to the `tournament.submitter_id` field.

`verified_by_user` can stay at the match-level.

**Comment by myssto** [comment]
We now identify the submitting user on both tournaments and matches. The change was merged with #173
