### ISSUE TITLE
Create `admin_comments` database table and associated entity

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#114]
We should create a `comments` table with the following structure:

Table Name - `admin_comments`
Structure:
- `id` (primary key)
- `created` (timestamp)
- `ref_id` (primary key of entity we are referencing)
- `entity_type` (`tournament`, `match`, `player`)
- `author_id` (`id` of the `user` that created this comment)
- `comment` (string, unlimited size)

Entity - `AdminComment : IEntity`
Structure:
- All above fields
- virtual `Author` (`User` that created the comment)

**Comment by myssto** [comment]
Being re-planned
