### ISSUE TITLE
Add `/players/restrict` `POST` endpoint

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#117]
An administrator should be able to restrict a user.

We should support the following query parameters:
- `?duration=<n days>` (null duration = infinite restriction).

Questions:
1. What does restriction actually *mean* from our perspective? Is it restricted from submitting tournaments? Is it restricted in the sense of foul play? (More than likely it is just from submitting tournaments). Whatever we decide, it should be documented (@cytusine0)

**Comment by cytusine0** [comment]
@hburn7 We did have a discussion a few weeks back about wanting a feature for excluding players like Fia from match cost calculations if they were found to be cheating or throwing. I do think we want some kind of marker for "restriction" of that kind, but it should be separate from the restriction from submitting tournaments. For our purposes I think restriction should include both submitting tournaments and tickets for modifications, and maybe we should find some other name for things related to being tourney restricted.
