### ISSUE TITLE
Add `comments` `POST`, `PATCH`, and `DELETE` endpoints for players, matches, and tournaments

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#121]
We need endpoints for manipulating comments. Some simple `POST`, `PATCH`, and `DELETE` endpoints for adding, editing, and deleting new comments is appropriate. 

Tasks:
- [ ] Tournament comments manipulation
  - [ ] `POST` `/tournaments/{id}/comments`
  - [ ] `PATCH` `/tournaments/{id}/comments`
  - [ ] `DELETE` `/tournaments/{id}/comments`
- [ ] Matches comments manipulation
  - [ ] `POST` `/matches/{id}/comments`
  - [ ] `PATCH` `/matches/{id}/comments`
  - [ ] `DELETE` `/matches/{id}/comments`
- [ ] Players comments manipulation
  - [ ] `POST` `/matches/{id}/comments`
  - [ ] `PATCH` `/matches/{id}/comments`
  - [ ] `DELETE` `/matches/{id}/comments`

Depends on #120

**Comment by myssto** [comment]
Updated to reflect our newer standards with resource oriented design

**Comment by myssto** [comment]
Being re-planned
