### ISSUE TITLE
Use consistent decorators and return values for endpoint methods

### ISSUE THREAD

**Issue by myssto** [osu-tournament-rating/otr-api#136]
Every method used as an endpoint within controllers should have a return value matching what the endpoint actually returns, not just `Task<IActionResult>`. These methods should also, at the bare minimum, employ the `[ProducesResponseType]`, `[EndpointSummary]`, and `[EndpointDescription]` decorators for consistency.

**Comment by hburn7** [comment]
After some research, I do agree we should not return the interface and instead return a concrete result. However, instead of ActionResult<T>, a recently introduced design pattern uses TypedResult<T>. I think the latter would be better, seems ActionResult is more on the legacy side nowadays.

**Comment by hburn7** [comment]
I don't know whether using a concrete return type and also using the attribute for ProducesResponseType<T> for 200 is necessary.

**Comment by myssto** [comment]
Yea, probably not necessary to use `ProducesResponseType` when using concrete return types, but a lot of methods are currently missing both

**Comment by myssto** [comment]
Using [this](https://learn.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-8.0) document as reference. After some more research and testing, as Stage suggested it looks like the best solution would be to go with using a return type of `Results<T>` (Defined [here](https://learn.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-8.0#resultstresult1-tresultn-type)). This approach leverages the static `TypedResults` class, and allows us to forego usage of the `ProducesResponseTypeAttribute`.

Consider the current endpoint `GET` `/api/v1/me`
```cs
    [HttpGet]
    [EndpointSummary("Gets the logged in user's information, if they exist")]
    [ProducesResponseType<UserInfoDTO>(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<ActionResult<UserInfoDTO>> GetLoggedInUserAsync()
```

Disregarding the fact that this incorrectly implements `ActionResult<T>` (As you would not need to include a type when using `[ProducesResponseType(StatusCodes.Status200OK)]`), this could be condensed into the following while maintaining swagger definitions:

```cs
    [HttpGet]
    [EndpointSummary("Gets the logged in user's information, if they exist")]
    public async Task<Results<BadRequest<string>, NotFound<string>, Ok<UserInfoDTO>>> GetLoggedInUserAsync()
```

Unfortunately the responses required to be used for this solution belong to `Microsoft.AspNetCore.Http.HttpResults`, and the default response methods inherited from `Microsoft.AspNetCore.Mvc.Controller` do not map to `TypedResult<T>`. So when returning a DTO, a response would have to look like `TypedResult.Ok(DTO)` instead of just `Ok(DTO)`. However I believe we could get around this by making an extension to `ControllerBase` that uses `TypedResult<T>` as a return instead.

**Comment by hburn7** [comment]
Yeah, I think TypedResult is perfect. Good find, Akinari will just have to go without error messages from us, I think the clients should be the ones generating these anyway based on our docs.

**Comment by myssto** [comment]
Perfect, I am working on consolidating some issues right now so I'll make sure this gets included
