### ISSUE TITLE
Refactor `/api/v1/matches/player/{osuId}` into `/api/v1/players/{key}/matches`

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#196]
`key` here is a dynamic search which we already have an implementation for. Aids #138

**Comment by hburn7** [comment]
Pretty sure this got fixed recently.

**Comment by myssto** [comment]
erm this endpoint actually got nuked somewhere along the way. The underlying service and repo methods still exist though so it should be an easy re-impl when the time comes.
