### ISSUE TITLE
Refactor all classes to use primary constructor parameters where possible

### ISSUE THREAD

**Issue by myssto** [osu-tournament-rating/otr-api#233]
As part of new .NET class constructor syntax, constructor variables are made available to the entire class (see [Primary Constructors](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/primary-constructors)). As discussed [here](https://github.com/osu-tournament-rating/otr-api/pull/228#discussion_r1548282324), we should be consistent in using this new style and avoid unnecessary `private readonly` instance variables.

Tasks
- [x] Refactor applicable classes to use primary constructor syntax
- [x] Add rule `csharp_style_prefer_primary_constructors` to `.editorconfig`

**Comment by Majorro** [comment]
@hburn7 may i take this? as it's a "good first issue"

**Comment by hburn7** [comment]
@Majorro Hi, thanks for asking. We are in the process of a very large rewrite at the moment, it's nearing completion. (see here: https://github.com/osu-tournament-rating/otr-api/tree/feature/data-processor-rewrite). Once this is merged, we can discuss next steps.

**Comment by majorro** [comment]
so, may I take this?

**Comment by myssto** [comment]
> so, may I take this?

Sure, go ahead
