### ISSUE TITLE
Group uncommon mods into 'other' category

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#244]
In player stats, we currently return all mods a user has played regardless of how small. If a mod is played less than 3% of the time, but more than 0%, we need to return these mods inside an `Other` mod category. This mod category should then contain the sum of the 'other' values and then contain the granular view of each remaining mod.

**Comment by myssto** [comment]
I think from the perspective of the api separated from web, we should continue returning mod stats as they are. I think it should fall on web to condense the mods smaller than the 5th most played etc. Returning mod stats in that format from the api would sort of dilute the data I feel. What do you think?

**Comment by hburn7** [comment]
This is going to be addressed in https://github.com/osu-tournament-rating/otr-web/issues/170
