### ISSUE TITLE
Average scores way too large in some cases

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#285]
Some users have very high average scores, i.e. [Crystal](https://dev.otr.stagec.xyz/users/740)

![image](https://github.com/osu-tournament-rating/otr-api/assets/38370573/96fb6dfa-3fb1-4243-be6b-122cc7d9b139)

ScoreV1 scores shouldn't be counted, same for invalid scores etc. We are probably not doing enough filtering on whatever query is responsible for this result.

**Comment by myssto** [comment]
This almost assuredly is being caused by changes made in #248. Currently waiting on a more up to date database dump so I can investigate.
