### ISSUE TITLE
Identify existing usages of `/players` endpoints

### ISSUE THREAD

**Issue by myssto** [osu-tournament-rating/otr-api#303]
Most endpoints of the `PlayersController` need to either be removed or refactored. To safely do this, their existing usages in the processor and web need to be identified. @S1n1st3rn3ss @AkinariHex @hburn7 Please comment on this issue any known usages of the below endpoints so we can have something to work off of.

Tasks:
- [x] Identify usage of `GET` `/players/all`
- [x] Identify usage of `GET` `/players/ranks/all`
- [x] Identify usage of `GET` `/players/id-mapping`
- [x] Identify usage of `GET` `/players/country-mapping`

**Comment by hburn7** [comment]
From what I see, otr-web does not use any of these endpoints.

The processor uses:
- `/players/ranks/all`
- `/players/country-mapping`

**Comment by hburn7** [comment]
Closing as most of these endpoints are no longer in use and have already been removed. #443 handles the rest.
