### ISSUE TITLE
Replace `mania` with `mania4k` and `mania7k`

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#333]
- [x] Map `Mania4k` to 4
- [x] Map `Mania7k` to 5
- [x] Ensure all tournaments in the database are updated appropriately (see [here](https://discord.com/channels/1100987119503151154/1101365295068745769/1249044105208528999))

**Comment by hburn7** [comment]
@myssto It seems that `Mania4k` and `Mania7k` are 4 and 5 respectively. Should web reflect this change as well?

**Comment by myssto** [comment]
> [@myssto](https://github.com/myssto) It seems that `Mania4k` and `Mania7k` are 4 and 5 respectively. Should web reflect this change as well?

Yes! Keeping `ManiaOther` as 3 is the easiest solution for backwards compatibility and submission with intent to reject etc. `Mania4k` should be 4 and `Mania7k` should be 5.

**Comment by myssto** [comment]
Updated the issue. The enum is mapped already but web should definitely reflect.
