### ISSUE TITLE
Rename `teamSize` to `lobbySize` in tournaments

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#337]
- [ ] Rename `teamSize` to `lobbySize` everywhere "team size" is used.
- [ ] Rename this in the tournaments db table.

**Comment by myssto** [comment]
Is this something we still want to do? There has been discussion here and there about it but personally I don't feel strongly either way

**Comment by hburn7** [comment]
I think I will make a poll.

**Comment by hburn7** [comment]
Will use `lobbySize` after community feedback.
