### ISSUE TITLE
Validate user dashboard stats returning as expected

### ISSUE THREAD

**Issue by AkinariHex** [osu-tournament-rating/otr-api#353]
When asking data to both endpoints `/me/stats` and `/stats/{id}` returns null and empty values.

Tested in branch: `feature/data-processor-rewrite`

![image](https://github.com/user-attachments/assets/9ba25b91-3207-48fa-9594-ec81684f8aef)
![image](https://github.com/user-attachments/assets/1c8e315b-6eef-49c5-a4b4-7982ca7fab23)

**Comment by hburn7** [comment]
I feel like this will be fixed once we get the new database populated

**Comment by hburn7** [comment]
Duplicate of #72
