### ISSUE TITLE
Move osu!track data to separate table

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#355]
We should store all relevant osu!track information in a separate table. This will allow us to query relevant osu!track information for a player. Should we wish to use osu!track for other purposes, we will have a lot more info to work with.

**Comment by hburn7** [comment]
@myssto didn't we do this? Not home to look at DB right now.

**Comment by myssto** [comment]
> @myssto didn't we do this? Not home to look at DB right now.

we did not

**Comment by myssto** [comment]
actually scratch that yes we did lmao
