### ISSUE TITLE
Implement service and repository methods to store `PlayerRating` objects

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#367]
Depends on #364, #362, #365

- [x] Create repository method
  - [x] Repository method stores associated `RatingAdjustment` child objects correctly
- [ ] Create service method to convert received `PlayerRatingDTO` objects to database objects.
  - [ ] Service method ensures that each match which has new `RatingAdjustment` data has the processing status set to `Done`

**Comment by Pantex9** [comment]
Hi, i am interested in resolving this issue.

**Comment by hburn7** [comment]
> Hi, i am interested in resolving this issue.

Hi there, apologies for marking your comment as spam. We did this as a precaution due to another comment appearing to be spam showing in our organization. Please join our Discord [here](https://discord.gg/R53AwX2tJA) if interested in contributing. Thanks!

**Comment by hburn7** [comment]
Repository and service classes are not needed as the processor is now able to connect to the database directly.
