### ISSUE TITLE
Create a `POST` endpoint with `system` only privileges to prep db for otr-processor

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#368]
- [ ] Add `/processor:truncate` `POST` endpoint
  - [ ] Endpoint truncates the `player_ratings` table (and by extension, the `rating_adjustments` table)
  - [ ] Endpoint is limited to `system` clients

**Comment by myssto** [comment]
Replaced by https://github.com/osu-tournament-rating/otr-processor/issues/68
