### ISSUE TITLE
Change all references of `otr-wiki` to `otr-docs` & update URLs where possible

### ISSUE THREAD

**Issue by myssto** [osu-tournament-rating/otr-api#369]
Some xml doc strings are linking to the defunct otr-wiki git repo. These should be changed to their respective otr-docs pages at docs.otr.stagec.xyz.

If a page doesn't yet exist, such as the Terms of Service page, it should be removed from Swagger / any docstrings.

**Comment by alixdotsh** [comment]
Ill do everything but the tos part since thats not even a thing

**Comment by myssto** [comment]
> Ill do everything but the tos part since thats not even a thing

See my response [here](https://github.com/osu-tournament-rating/otr-api/pull/402#pullrequestreview-2305611217). I'd rather we open up an issue to get that doc created then half-complete this issue
