### ISSUE TITLE
Identify and implement a more reliable method of applying database migrations for deployments

### ISSUE THREAD

**Issue by myssto** [osu-tournament-rating/otr-api#375]
Currently the API is responsible for applying database migrations via the context during startup. This worked perfectly fine for a monolithic architecture where we knew that the API was the only point of access for the database. Now that we are deploying multiple microservices that will be accessing the database independently of each other, this method can create problems if a microservice is expecting a certain database schema before the API is able to perform a migration during deployment (think race conditions). This specific strategy is documented [here](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli#apply-migrations-at-runtime) in the EF Core documentation.

- [x] Identify a strategy for applying new migrations during deployment
- [x] Integrate new strategy into deployment
- [x] Test new strategy
- [x] Remove existing code for applying migrations within the `otr-api`

**Comment by hburn7** [comment]
Could we move the logic into a shared utility class and call the same code in the Program file? We will redeploy all projects regardless of what is changed anyway.

**Comment by hburn7** [comment]
We now use EF migration scripts, documented here. https://docs.otr.stagec.xyz/database-setup-backup-and-recovery.html#migrations
