### ISSUE TITLE
Create a `POST`, `PATCH`, and `DELETE` endpoint for each admin note entity and establish access layers

### ISSUE THREAD

**Issue by myssto** [osu-tournament-rating/otr-api#379]
Depends on #378

Admin notes need API routes for CRUD actions. They should be routed like: 

`POST` `/{entity}/{id}/notes`
`GET` `/{entity}/{id}/notes`
`PATCH` `/{entity}/{id}/notes/{noteId}`
`DELETE` `/{entity}/{id}/notes/{noteId}`

Admin notes should be included on the entity's existing DTO for admin users only.

# Tasks

Implement the four endpoints (and `AdminNote` repository / service layers) for these entities:

**Base classes**
- [x] `AdminNoteRepositoryBase` #431
- [x] `AdminNoteService` #431

- **Tournament** #433
  - [x] `POST`
  - [x] `GET`
  - [x] `PATCH`
  - [x] `DELETE`

- **Match** #456
  - [x] `POST`
  - [x] `GET`
  - [x] `PATCH`
  - [x] `DELETE`

- **Game** #457 
  - [x] `POST`
  - [x] `GET`
  - [x] `PATCH`
  - [x] `DELETE`

- **GameScore** #458
  - [x] `POST`
  - [x] `GET`
  - [x] `PATCH`
  - [x] `DELETE`

- **Player** #459
  - [x] `POST`
  - [x] `GET`
  - [x] `PATCH`
  - [x] `DELETE`

**Comment by hburn7** [comment]
Removed `OAuthClient` and `Player` from the scope of this issue as they are not particularly relevant right now. (i.e., I don't see a use for admin notes in either of these entities currently). We also don't have a UI for that yet.

**Comment by hburn7** [comment]
Closed once #456, #457, #458, and #459 are merged.
