### ISSUE TITLE
Use data annotations in `LeaderboardRequestQueryDTO`

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#447]
Every check in `LeaderboardService.cs` needs to be converted to a data annotation in the `LeaderboardRequestQueryDTO` class.

- [x] Use data annotations in `LeaderboardRequestQueryDTO`
- [x] Use data annotations in `LeaderboardFilterDTO`
- [x] Modify `LeaderboardService.ValidateRequest()` such that it only checks for sensible property comparisons. e.g. `minRank > maxRank` should be impossible.

**Comment by hammockryan8** [comment]
assigning this to myself

**Comment by hburn7** [comment]
327fbdd950e68fe4e08297c3c93e827cec1a3235 Added some annotations here. Still need to add to `LeaderboardFilterDTO`. Also, the `ValidateRequest` method can stay because there isn't a way (outside of custom validation attributes) to compare two properties during runtime. However, that method needs to change to **only** be used for comparisons between two properties.

**Comment by hburn7** [comment]
@myssto As of #544 what's the status of this one?

**Comment by myssto** [comment]
> @myssto As of #544 what's the status of this one?

#544 closes this :)
