### ISSUE TITLE
Update `OsuApiDataParserService` to update beatmaps which have only the `OsuId` field populated

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#472]
Part of #438 

# Overview

We need the `OsuApiDataParserService` to update beatmaps which only have the `OsuId` field populated. The reason for this is that users are now expected to submit beatmap ids in the tournament submission process. As a result, beatmaps need to be "processed" in a very similar way to that of matches.

To remain consistent with other processable entities, we should introduce a `processing_status` field on the `beatmaps` table. This enum can have two states for now: `NeedsData = 0` and `Done = 1`. I don't think it's necessary to store the result of the processing, i.e. `NoDataFound`, because it is implied that a beatmap with a status of `1` is already populated with as much available data as possible.

# Tasks

- [ ] In `OsuApiDataParserService`, change the behavior such that beatmaps with a `ProcessingStatus` of `NeedsData` are polled and updated accordingly.
- [ ] Set the `ProcessingStatus` to `Done` at the end of processing regardless of whether data exists for the particular beatmap.

**Comment by myssto** [comment]
Discussed in discord already but this is not necessary. We can make good enough assumptions based on what we know about our structure and the data from the osu! API to effectively process beatmaps.
