### ISSUE TITLE
Use `RequiredAttribute` for non-optional query parameters

### ISSUE THREAD

**Issue by myssto** [osu-tournament-rating/otr-api#524]
This one is strictly code quality and is useful for the swagger generator. By default the swagger generator will assume that query parameters are optional when in some cases they aren't. We should annotate required query parameters with the `System.ComponentModel.DataAnnotations.RequiredAttribute` to be more verbose.

For example currently (From the `OAuthController`):
```cs
public async Task<IActionResult> AuthorizeClientAsync(
    [FromQuery] int clientId, 
    [FromQuery] string clientSecret
)
```

Since the `clientId` and `clientSecret` are required query parameters, it could be annotated like so:
```cs
public async Task<IActionResult> AuthorizeClientAsync(
    [FromQuery] [Required] int clientId,
    [FromQuery] [Required] string clientSecret
)
```

**Comment by hburn7** [comment]
I think separate brackets is fine
