### ISSUE TITLE
Have more useful logs in `DataWorkerService`

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#545]
Currently, I have the following issues with the logs in the DataWorker:

1. It's impossible to tell what is actually going on at a glance.
2. The logs spam the console and are basically useless outside of a trace scenario.

I'd like to see the following changes:

1. Tournament and match processing logs are changed to Debug severity.
2. Game and GameScore processing logs are changed to Trace severity.
3. (Info severity): A summary is reported after a tournament completes processing which contains the number of Matches, Games, and Scores grouped by verification status and rejection reason. Basically a full report per tournament.

Questions:

1. Do we ever have a scenario where we want to re-process specific matches? If so, we should look into how we can have these logs show up in an informative way. If not, all match logs can be marked as Debug.

**Comment by myssto** [comment]
> 3. (Info severity): A summary is reported after a tournament completes processing which contains the number of Matches, Games, and Scores grouped by verification status and rejection reason. Basically a full report per tournament.

Can you elaborate more on what you would like this to look like?

**Comment by hburn7** [comment]
Closed in #547 and #549
